### ISSUE TITLE
Create Firefox Role

### ISSUE THREAD

**Issue by gderber** [bloodymage/ansible-collection-rebeldream#114]
Requirements:
- [x] Must install Firefox
- [x] Must install Certificate Authority Certs #56 
- [x] Must install Client Certs #60
- [x] Must include README.md #47
- [x] Must create global configuration for GSSAPI logon #20 
- [ ] Must configure Global Policy Object on windows hosts #19

**Comment by gderber** [comment]
Closing, the last part will be added in the 0.8 release with the other windows sertings
